config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "main#index"
  get  "sign_up" ,to: "registration#new"
  post "sign_up" ,to: "registration#create"
  
  get  "password/resets" ,to: "password_resets#new"
  post "password/resets" ,to: "password_resets#create"
  
  get  "password/resets/edit" ,to: "password_resets#edit"
  patch "password/resets/edit" ,to: "password_resets#update"
  
  get  "password" ,to: "passwords#edit" ,as: :edit_password
  patch "password" ,to: "passwords#update"
  
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "sign_out" ,to: "sessions#destroy"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_rich_text :content
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(user_id: Current.user.id, title: params[:article][:title], content: params[:article][:content])

    respond_to do |format|
      if @article.save
         flash[:notice] = "Article was successfully created"
        format.html { redirect_to article_url(@article)}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article" id="<%= dom_id article %>">
  <p class="head">
    <%= article.title %>
  </p>
  
  <div class="content">
    <%= article.content  %>
  </div>

  
  <div  class="content">
    <i class="fa-solid fa-user"></i>
    <%=link_to article.user.name, user_path(article.user),
       :class => "userLink lefter"%>
  </div>
  
  <div  class="content">
    <strong>Posted:</strong>
      <%=((Time.current - article.created_at)/1.minute).round %>
    <span>minutes ago</span>
  </div>
 
</div>

app/views/articles/_comments.html.erb
<h2>comments</h2>
<div id="comments">
<%= render article.comments%>
</div>
<%= render "comments/form",article:article%>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

<%
=begin%>
   <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id,User.all ,:id ,:name %>
  </div>
 
<%
=end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title">Articles</h1>
<% if Current.user %>
<p>
<%= link_to "New article", new_article_path %>
</p>
<%end%>

<div id="articles" class="content">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
    <% if Current.user %>
      <%= link_to "Show this article", article %>
    <%end%>
    </p>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article ,:class => "content" %>
<%= render "articles/comments",article:@article%>

<div>
  <% if @article.user.userName== Current.user.userName%>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= button_to "Destroy this article", @article, method: :delete %>
  <%end%>
  <%= link_to "Back to articles", articles_path %>
</div>