config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "main#index"
  get  "sign_up" ,to: "registration#new"
  post "sign_up" ,to: "registration#create"
  
  get  "password/resets" ,to: "password_resets#new"
  post "password/resets" ,to: "password_resets#create"
  
  get  "password/resets/edit" ,to: "password_resets#edit"
  patch "password/resets/edit" ,to: "password_resets#update"
  
  get  "password" ,to: "passwords#edit" ,as: :edit_password
  patch "password" ,to: "passwords#update"
  
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "sign_out" ,to: "sessions#destroy"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
     <%=link_to "BLOG" ,articles_path ,:class=>"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to "Articles" ,articles_path ,:class=>"nav-link active" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">
        <% if Current.user%>
          <li class="nav-item navbar-brand"> 
            <%=link_to Current.user.userName,edit_password_path ,:class=>"nav-link"%>
          </li>
          <li class="nav-item">  
            <%=button_to "signout",sign_out_path,method: :delete ,:class=>"btn btn-danger"%>
          </li>
        <%else %>
          <li class="nav-item"> 
            <%=link_to "Sign In" ,sign_in_path  ,:class=>"nav-link"%>
          </li>

          <li class="nav-item"> 
            <%=link_to "Sign Up" ,sign_up_path ,:class=>"nav-link" %>
          </li>

        <%end%>
      </ul>
    </div>
  </div>
</nav>